### ISSUE TITLE
Hook up start/end dates

### ISSUE THREAD

**Issue by erfangc** [erfangc/DecoratedStockChart#8]
`startDate` `endDate` should be optionally passed in as a *non*-binding scope option (i think)

after which point, when they are changed by the user, it should trigger some behavior 

(i.e. take a look at all security series currently plotted then re-invoke the callbacks that created them in the first place with the new dates .. and then do the same for the non-security series)

**Comment by caguthrie** [comment]
If we make it a non-binding scope option the user can only pass in strings or numbers as date representations and not Date objects.  How do you feel about that.

**Comment by erfangc** [comment]
I think that is fine. or we can make it binding if that make things easier and more intuitive. Either way is fine I think

**Comment by caguthrie** [comment]
Done with most in. 26746c083c8606879aff1f6d2eb7b7da574d2cda ... TODO validation if extremes are too extreme (i.e. off the dataset)

**Comment by erfangc** [comment]
this is done right? I am closing it
